version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/philippgeyer.co.uk
hooks:
  AfterInstall:
    - location: scripts/permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/build.sh
      timeout: 300
      runas: ec2-user